import A7 as c
x=int(input("enter the first no :"))
y=int(input("enter the second no :"))
r=c.add(x,y)
print(f"sum={r}")
r=c.sub(x,y)
print(f"substraction={r}")
r=c.mul(x,y)
print(f"multiplication={r}")
r=c.div(x,y)
print(f"division={r}")